"""v5

Revision ID: 56635c1b0b2c
Revises: 122460e4ac92
Create Date: 2023-11-23 05:43:54.604510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56635c1b0b2c'
down_revision = '122460e4ac92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('my_modul',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_modul', sa.Integer(), nullable=True),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_modul'], ['modul.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('modul', schema=None) as batch_op:
        batch_op.add_column(sa.Column('path_modul', sa.String(length=255), nullable=True))
        batch_op.alter_column('namamodul',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=200),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modul', schema=None) as batch_op:
        batch_op.alter_column('namamodul',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)
        batch_op.drop_column('path_modul')

    op.drop_table('my_modul')
    # ### end Alembic commands ###
