"""versi

Revision ID: ad4e167f48b6
Revises: 4b60c0257763
Create Date: 2023-11-23 03:52:01.798137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad4e167f48b6'
down_revision = '4b60c0257763'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modul',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('namamodul', sa.String(length=30), nullable=True),
    sa.Column('keterangan', sa.String(length=400), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('modul')
    # ### end Alembic commands ###
