"""v1.0

Revision ID: fab9cf60c7c4
Revises: 
Create Date: 2023-11-22 05:21:55.498484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fab9cf60c7c4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('namalengkap', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=35), nullable=True),
    sa.Column('password_hash', sa.String(length=163), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
